"""add_must_have_tags_season_fit_to_clusters

Revision ID: 204fa6789b76
Revises: 20260323_030000
Create Date: 2026-03-23 12:39:16.288650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '204fa6789b76'
down_revision: Union[str, Sequence[str], None] = '20260323_030000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quiz_submissions')
    op.alter_column('activity_clusters', 'default_duration',
               existing_type=sa.VARCHAR(length=20),
               comment='full_day / half_day / quarter_day — 展示标签，内部用分钟字段',
               existing_comment='full_day / half_day / quarter_day',
               existing_nullable=True)
    op.alter_column('activity_clusters', 'fatigue_weight',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               comment='体力消耗系数：0.5轻松/1.0正常/1.5耗体力，影响带老人/小孩折扣',
               existing_comment='体力消耗系数：0.5轻松/1.0正常/1.5耗体力',
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('activity_clusters', 'best_time_window',
               existing_type=sa.VARCHAR(length=50),
               comment="如 '07:00-09:00' (早间) / 'evening' / 'anytime'",
               existing_comment="如 '07:00-09:00' / 'evening' / 'anytime'",
               existing_nullable=True)
    op.alter_column('entity_base', 'nearest_station',
               existing_type=sa.VARCHAR(length=100),
               comment='最近地铁/车站名称',
               existing_nullable=True)
    op.alter_column('entity_base', 'corridor_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment="所属走廊标签列表，如 ['higashiyama', 'gion']",
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('entity_base', 'typical_duration_baseline',
               existing_type=sa.SMALLINT(),
               comment='基准游览时长（分钟），非时态值，时态值在 entity_temporal_profiles',
               existing_nullable=True)
    op.alter_column('entity_base', 'price_band',
               existing_type=sa.VARCHAR(length=10),
               comment='free / budget / mid / premium / luxury',
               existing_nullable=True)
    op.alter_column('entity_base', 'operating_stability_level',
               existing_type=sa.VARCHAR(length=10),
               comment='stable / moderate / volatile',
               existing_nullable=True)
    op.alter_column('entity_media', 'source_kind',
               existing_type=sa.VARCHAR(length=30),
               comment='official_site / official_social / google_places / licensed_partner / manual_upload / other_candidate',
               existing_nullable=True)
    op.alter_column('entity_media', 'source_page_url',
               existing_type=sa.TEXT(),
               comment='图片来源页面 URL（溯源用）',
               existing_nullable=True)
    op.alter_column('entity_media', 'attribution_text',
               existing_type=sa.VARCHAR(length=500),
               comment='归属文本（Google Places 要求展示）',
               existing_nullable=True)
    op.alter_column('entity_media', 'license_status',
               existing_type=sa.VARCHAR(length=20),
               comment='allowed / restricted / review_needed',
               existing_nullable=True,
               existing_server_default=sa.text("'review_needed'::character varying"))
    op.alter_column('entity_media', 'image_role',
               existing_type=sa.VARCHAR(length=30),
               comment='hero / exterior / lobby / room / bath / breakfast / signature_dish / interior / menu / main_scene / entrance / transit_hint / experience',
               existing_nullable=True)
    op.alter_column('entity_media', 'quality_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='0-10 图片质量评分（清晰度+构图+代表性）',
               existing_nullable=True)
    op.alter_column('entity_media', 'representativeness_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment='0-10 图片对实体的代表性评分',
               existing_nullable=True)
    op.alter_column('entity_media', 'season_tag',
               existing_type=sa.VARCHAR(length=20),
               comment='spring / summer / autumn / winter / all_season',
               existing_nullable=True)
    op.alter_column('entity_media', 'daypart_tag',
               existing_type=sa.VARCHAR(length=20),
               comment='day / sunset / night / all_day',
               existing_nullable=True)
    op.alter_column('entity_media', 'is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='精选标记（从候选池进入最终展示）',
               existing_server_default=sa.text('false'))
    op.alter_column('entity_media', 'needs_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               comment='是否需要人工审核',
               existing_server_default=sa.text('true'))
    op.alter_column('entity_media', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_entity_media_review', 'entity_media', ['needs_review', 'license_status'], unique=False)
    op.create_index('ix_entity_media_role', 'entity_media', ['image_role'], unique=False)
    op.create_index('ix_entity_media_selected', 'entity_media', ['entity_id', 'is_selected'], unique=False)
    op.alter_column('entity_scores', 'preview_score',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               comment='预览分 0-100',
               existing_nullable=True)
    op.alter_column('entity_scores', 'context_score',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               comment='上下文分 0-100',
               existing_nullable=True)
    op.alter_column('entity_scores', 'soft_rule_score',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=5, scale=2),
               comment='软规则分 0-100',
               existing_nullable=True)
    op.alter_column('entity_scores', 'soft_rule_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='软规则维度分详情',
               existing_nullable=True)
    op.alter_column('entity_scores', 'segment_pack_id',
               existing_type=sa.VARCHAR(length=50),
               comment='使用的客群权重包',
               existing_nullable=True)
    op.alter_column('entity_scores', 'stage_pack_id',
               existing_type=sa.VARCHAR(length=50),
               comment='使用的阶段权重包',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'time_sensitivity',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='timeless / soft_ttl / hard_ttl / snapshot_bound',
               existing_server_default=sa.text("'timeless'::character varying"))
    op.alter_column('guide_fragments', 'ttl_days',
               existing_type=sa.INTEGER(),
               comment='soft/hard TTL 天数',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='生效起始时间',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='失效时间',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'refresh_strategy',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               comment='none / downgrade / block / snapshot_refill',
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('itinerary_items', 'swap_candidates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='替换候选列表',
               existing_nullable=True)
    op.alter_column('itinerary_plans', 'report_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='3层攻略报告正文: {layer1_overview, layer2_daily, layer3_appendix}',
               existing_nullable=True)
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='new / sample_viewed / paid / detail_filling / detail_submitted / validating / needs_fix / validated / generating / done / delivered / cancelled / refunded',
               existing_comment='pending / paid / processing / delivered / refunded',
               existing_nullable=False)
    op.add_column('trip_profiles', sa.Column('pace', sa.String(length=20), nullable=True, comment='relaxed / moderate / packed'))
    op.alter_column('trip_profiles', 'budget_focus',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=30),
               comment='better_stay / better_food / better_experience / balanced / best_value',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'arrival_shape',
               existing_type=sa.VARCHAR(length=30),
               comment='one_way / open_jaw / same_city — 到达/离开形态',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'departure_shape',
               existing_type=sa.VARCHAR(length=30),
               comment='与 arrival_shape 配合，描述离开端',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'arrival_airport',
               existing_type=sa.VARCHAR(length=10),
               comment='NRT / HND / KIX / ...',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'departure_airport',
               existing_type=sa.VARCHAR(length=10),
               comment='NRT / HND / KIX / ...',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'last_flight_time',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=5),
               comment='HH:MM 返程航班时间，用于最后一晚安全计算',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'daytrip_tolerance',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               comment='low / medium / high — 日归容忍度',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'hotel_switch_tolerance',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               comment='low / medium / high — 换酒店容忍度',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'wake_up_time',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               comment='early / normal / late',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'arrival_day_shape',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               comment='full_day / half_day_afternoon / evening_only / red_eye — 到达日可用时段',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'departure_day_shape',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=20),
               comment='full_day / half_day_morning / early_morning — 离开日可用时段',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'accommodation_pref',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='住宿偏好详情',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'flight_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='航班详情 {outbound:{...}, return:{...}}',
               existing_nullable=True)
    op.alter_column('trip_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='new / sample_viewed / paid / detail_filling / detail_submitted / validating / needs_fix / validated / generating / done / delivered / cancelled / refunded',
               existing_comment='pending / normalizing / profiled / planning / done / failed',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trip_requests', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending / normalizing / profiled / planning / done / failed',
               existing_comment='new / sample_viewed / paid / detail_filling / detail_submitted / validating / needs_fix / validated / generating / done / delivered / cancelled / refunded',
               existing_nullable=False)
    op.alter_column('trip_profiles', 'flight_info',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='航班详情 {outbound:{...}, return:{...}}',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'accommodation_pref',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='住宿偏好详情',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'departure_day_shape',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='full_day / half_day_morning / early_morning — 离开日可用时段',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'arrival_day_shape',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='full_day / half_day_afternoon / evening_only / red_eye — 到达日可用时段',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'wake_up_time',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='early / normal / late',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'hotel_switch_tolerance',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='low / medium / high — 换酒店容忍度',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'daytrip_tolerance',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='low / medium / high — 日归容忍度',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'last_flight_time',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='HH:MM 返程航班时间，用于最后一晚安全计算',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'departure_airport',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='NRT / HND / KIX / ...',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'arrival_airport',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='NRT / HND / KIX / ...',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'departure_shape',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='与 arrival_shape 配合，描述离开端',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'arrival_shape',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='one_way / open_jaw / same_city — 到达/离开形态',
               existing_nullable=True)
    op.alter_column('trip_profiles', 'budget_focus',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='better_stay / better_food / better_experience / balanced / best_value',
               existing_nullable=True)
    op.drop_column('trip_profiles', 'pace')
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='pending / paid / processing / delivered / refunded',
               existing_comment='new / sample_viewed / paid / detail_filling / detail_submitted / validating / needs_fix / validated / generating / done / delivered / cancelled / refunded',
               existing_nullable=False)
    op.alter_column('itinerary_plans', 'report_content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='3层攻略报告正文: {layer1_overview, layer2_daily, layer3_appendix}',
               existing_nullable=True)
    op.alter_column('itinerary_items', 'swap_candidates',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='替换候选列表',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'refresh_strategy',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='none / downgrade / block / snapshot_refill',
               existing_server_default=sa.text("'none'::character varying"))
    op.alter_column('guide_fragments', 'valid_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='失效时间',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'valid_from',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='生效起始时间',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'ttl_days',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='soft/hard TTL 天数',
               existing_nullable=True)
    op.alter_column('guide_fragments', 'time_sensitivity',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               comment=None,
               existing_comment='timeless / soft_ttl / hard_ttl / snapshot_bound',
               existing_server_default=sa.text("'timeless'::character varying"))
    op.alter_column('entity_scores', 'stage_pack_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='使用的阶段权重包',
               existing_nullable=True)
    op.alter_column('entity_scores', 'segment_pack_id',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='使用的客群权重包',
               existing_nullable=True)
    op.alter_column('entity_scores', 'soft_rule_breakdown',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment='软规则维度分详情',
               existing_nullable=True)
    op.alter_column('entity_scores', 'soft_rule_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               comment=None,
               existing_comment='软规则分 0-100',
               existing_nullable=True)
    op.alter_column('entity_scores', 'context_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               comment=None,
               existing_comment='上下文分 0-100',
               existing_nullable=True)
    op.alter_column('entity_scores', 'preview_score',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.REAL(),
               comment=None,
               existing_comment='预览分 0-100',
               existing_nullable=True)
    op.drop_index('ix_entity_media_selected', table_name='entity_media')
    op.drop_index('ix_entity_media_role', table_name='entity_media')
    op.drop_index('ix_entity_media_review', table_name='entity_media')
    op.alter_column('entity_media', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('entity_media', 'needs_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='是否需要人工审核',
               existing_server_default=sa.text('true'))
    op.alter_column('entity_media', 'is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               comment=None,
               existing_comment='精选标记（从候选池进入最终展示）',
               existing_server_default=sa.text('false'))
    op.alter_column('entity_media', 'daypart_tag',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='day / sunset / night / all_day',
               existing_nullable=True)
    op.alter_column('entity_media', 'season_tag',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='spring / summer / autumn / winter / all_season',
               existing_nullable=True)
    op.alter_column('entity_media', 'representativeness_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='0-10 图片对实体的代表性评分',
               existing_nullable=True)
    op.alter_column('entity_media', 'quality_score',
               existing_type=sa.NUMERIC(precision=4, scale=2),
               comment=None,
               existing_comment='0-10 图片质量评分（清晰度+构图+代表性）',
               existing_nullable=True)
    op.alter_column('entity_media', 'image_role',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='hero / exterior / lobby / room / bath / breakfast / signature_dish / interior / menu / main_scene / entrance / transit_hint / experience',
               existing_nullable=True)
    op.alter_column('entity_media', 'license_status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='allowed / restricted / review_needed',
               existing_nullable=True,
               existing_server_default=sa.text("'review_needed'::character varying"))
    op.alter_column('entity_media', 'attribution_text',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='归属文本（Google Places 要求展示）',
               existing_nullable=True)
    op.alter_column('entity_media', 'source_page_url',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='图片来源页面 URL（溯源用）',
               existing_nullable=True)
    op.alter_column('entity_media', 'source_kind',
               existing_type=sa.VARCHAR(length=30),
               comment=None,
               existing_comment='official_site / official_social / google_places / licensed_partner / manual_upload / other_candidate',
               existing_nullable=True)
    op.alter_column('entity_base', 'operating_stability_level',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='stable / moderate / volatile',
               existing_nullable=True)
    op.alter_column('entity_base', 'price_band',
               existing_type=sa.VARCHAR(length=10),
               comment=None,
               existing_comment='free / budget / mid / premium / luxury',
               existing_nullable=True)
    op.alter_column('entity_base', 'typical_duration_baseline',
               existing_type=sa.SMALLINT(),
               comment=None,
               existing_comment='基准游览时长（分钟），非时态值，时态值在 entity_temporal_profiles',
               existing_nullable=True)
    op.alter_column('entity_base', 'corridor_tags',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment=None,
               existing_comment="所属走廊标签列表，如 ['higashiyama', 'gion']",
               existing_nullable=True,
               existing_server_default=sa.text("'[]'::jsonb"))
    op.alter_column('entity_base', 'nearest_station',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment='最近地铁/车站名称',
               existing_nullable=True)
    op.alter_column('activity_clusters', 'best_time_window',
               existing_type=sa.VARCHAR(length=50),
               comment="如 '07:00-09:00' / 'evening' / 'anytime'",
               existing_comment="如 '07:00-09:00' (早间) / 'evening' / 'anytime'",
               existing_nullable=True)
    op.alter_column('activity_clusters', 'fatigue_weight',
               existing_type=sa.NUMERIC(precision=3, scale=1),
               comment='体力消耗系数：0.5轻松/1.0正常/1.5耗体力',
               existing_comment='体力消耗系数：0.5轻松/1.0正常/1.5耗体力，影响带老人/小孩折扣',
               existing_nullable=True,
               existing_server_default=sa.text('1.0'))
    op.alter_column('activity_clusters', 'default_duration',
               existing_type=sa.VARCHAR(length=20),
               comment='full_day / half_day / quarter_day',
               existing_comment='full_day / half_day / quarter_day — 展示标签，内部用分钟字段',
               existing_nullable=True)
    op.create_table('quiz_submissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('destination', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('duration_days', sa.INTEGER(), server_default=sa.text('7'), autoincrement=False, nullable=False),
    sa.Column('people_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('party_type', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('japan_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('play_mode', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('budget_focus', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('styles', postgresql.ARRAY(sa.TEXT()), server_default=sa.text('ARRAY[]::text[]'), autoincrement=False, nullable=True),
    sa.Column('wechat_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'new'::text"), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('travel_end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('quiz_submissions_pkey'))
    )
    # ### end Alembic commands ###
