"""initial_schema — create all 35 tables

Revision ID: a1b2c3d4e5f6
Revises: 6def7e8a5f32
Create Date: 2026-03-19

Hand-written migration covering all 35 tables defined in the ORM models.
Generated by inspecting Base.metadata after all models are imported.
Equivalent to running: alembic revision --autogenerate -m "initial_schema"
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID

try:
    from pgvector.sqlalchemy import VECTOR
except ImportError:  # pgvector may not be installed in CI without PG
    from sqlalchemy import String as VECTOR  # type: ignore[misc]  # noqa: F811

# revision identifiers
revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = "6def7e8a5f32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ── users ──
    op.create_table('users',
        sa.Column('user_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('openid', sa.String(200)),
        sa.Column('phone', sa.String(20)),
        sa.Column('nickname', sa.String(100)),
        sa.Column('avatar_url', sa.Text()),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )

    # ── product_sku ──
    op.create_table('product_sku',
        sa.Column('sku_id', sa.String(50), primary_key=True),
        sa.Column('sku_name', sa.String(100), nullable=False),
        sa.Column('price_cny', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column('sku_type', sa.String(20), nullable=False),
        sa.Column('features', JSONB(), nullable=False),
        sa.Column('max_days', sa.SmallInteger()),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )

    # ── entity_base ──
    op.create_table('entity_base',
        sa.Column('entity_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('entity_type', sa.String(20), nullable=False),
        sa.Column('name_zh', sa.String(200), nullable=False),
        sa.Column('name_ja', sa.String(200)),
        sa.Column('name_en', sa.String(200)),
        sa.Column('city_code', sa.String(50), nullable=False),
        sa.Column('prefecture', sa.String(50)),
        sa.Column('area_name', sa.String(100)),
        sa.Column('address_ja', sa.String(500)),
        sa.Column('address_en', sa.String(500)),
        sa.Column('lat', sa.Numeric(precision=10, scale=7)),
        sa.Column('lng', sa.Numeric(precision=10, scale=7)),
        sa.Column('embedding', sa.Text()),  # VECTOR(1536) — created as text, cast manually if pgvector available
        sa.Column('data_tier', sa.String(1), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('google_place_id', sa.String(200)),
        sa.Column('tabelog_id', sa.String(200)),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )
    # Re-add embedding as vector(1536) after extension is enabled
    op.execute("ALTER TABLE entity_base ALTER COLUMN embedding TYPE vector(1536) USING NULL")

    # ── render_templates ──
    op.create_table('render_templates',
        sa.Column('render_template_id', sa.BigInteger(), primary_key=True),
        sa.Column('template_name', sa.String(100), nullable=False),
        sa.Column('template_type', sa.String(20), nullable=False),
        sa.Column('html_content', sa.Text(), nullable=False),
        sa.Column('css_content', sa.Text()),
        sa.Column('version', sa.String(20), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )

    # ── source_snapshots ──
    op.create_table('source_snapshots',
        sa.Column('snapshot_id', sa.BigInteger(), primary_key=True),
        sa.Column('source_name', sa.String(50), nullable=False),
        sa.Column('object_type', sa.String(30), nullable=False),
        sa.Column('object_id', sa.String(200), nullable=False),
        sa.Column('raw_payload', JSONB(), nullable=False),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
        sa.Column('http_status', sa.SmallInteger()),
        sa.Column('request_url', sa.Text()),
    )

    # ── flight_offer_snapshots ──
    op.create_table('flight_offer_snapshots',
        sa.Column('flight_snapshot_id', sa.BigInteger(), primary_key=True),
        sa.Column('origin_iata', sa.String(3), nullable=False),
        sa.Column('dest_iata', sa.String(3), nullable=False),
        sa.Column('departure_date', sa.String(10), nullable=False),
        sa.Column('return_date', sa.String(10)),
        sa.Column('source_name', sa.String(50), nullable=False),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
        sa.Column('currency', sa.String(3), nullable=False),
        sa.Column('min_price', sa.Numeric(precision=10, scale=2)),
        sa.Column('raw_payload', JSONB()),
    )

    # ── weather_snapshots ──
    op.create_table('weather_snapshots',
        sa.Column('weather_snapshot_id', sa.BigInteger(), primary_key=True),
        sa.Column('city_code', sa.String(50), nullable=False),
        sa.Column('forecast_date', sa.String(10), nullable=False),
        sa.Column('source_name', sa.String(50), nullable=False),
        sa.Column('temp_high_c', sa.Numeric(precision=4, scale=1)),
        sa.Column('temp_low_c', sa.Numeric(precision=4, scale=1)),
        sa.Column('condition', sa.String(30)),
        sa.Column('precipitation_mm', sa.Numeric(precision=5, scale=1)),
        sa.Column('raw_payload', JSONB()),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
    )

    # ── route_matrix_cache ──
    op.create_table('route_matrix_cache',
        sa.Column('cache_id', sa.BigInteger(), primary_key=True),
        sa.Column('origin_entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('dest_entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('travel_mode', sa.String(20), nullable=False),
        sa.Column('duration_min', sa.SmallInteger(), nullable=False),
        sa.Column('distance_km', sa.Numeric(precision=6, scale=2)),
        sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
    )

    # ── route_templates ──
    op.create_table('route_templates',
        sa.Column('template_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('name_zh', sa.String(200), nullable=False),
        sa.Column('city_code', sa.String(50), nullable=False),
        sa.Column('duration_days', sa.SmallInteger(), nullable=False),
        sa.Column('theme', sa.String(50)),
        sa.Column('sku_tier', sa.String(10), nullable=False),
        sa.Column('template_data', JSONB(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )

    # ── review_jobs ──
    op.create_table('review_jobs',
        sa.Column('review_job_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('job_type', sa.String(30), nullable=False),
        sa.Column('target_id', sa.String(200), nullable=False),
        sa.Column('target_type', sa.String(30), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('assigned_to', sa.String(100)),
        sa.Column('priority', sa.SmallInteger(), nullable=False),
        sa.Column('deadline', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
    )

    # ── pois ──
    op.create_table('pois',
        sa.Column('entity_id', UUID(as_uuid=True), primary_key=True),
        sa.Column('poi_category', sa.String(50)),
        sa.Column('sub_category', sa.String(50)),
        sa.Column('typical_duration_min', sa.SmallInteger()),
        sa.Column('opening_hours_json', JSONB()),
        sa.Column('admission_fee_jpy', sa.Integer()),
        sa.Column('admission_free', sa.Boolean(), nullable=False),
        sa.Column('best_season', sa.String(20)),
        sa.Column('crowd_level_typical', sa.String(10)),
        sa.Column('requires_advance_booking', sa.Boolean(), nullable=False),
        sa.Column('google_rating', sa.Numeric(precision=3, scale=1)),
        sa.Column('google_review_count', sa.Integer()),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── hotels ──
    op.create_table('hotels',
        sa.Column('entity_id', UUID(as_uuid=True), primary_key=True),
        sa.Column('hotel_type', sa.String(30)),
        sa.Column('star_rating', sa.Numeric(precision=2, scale=1)),
        sa.Column('chain_name', sa.String(100)),
        sa.Column('room_count', sa.SmallInteger()),
        sa.Column('check_in_time', sa.String(5)),
        sa.Column('check_out_time', sa.String(5)),
        sa.Column('amenities', JSONB()),
        sa.Column('is_family_friendly', sa.Boolean(), nullable=False),
        sa.Column('is_pet_friendly', sa.Boolean(), nullable=False),
        sa.Column('price_tier', sa.String(10)),
        sa.Column('typical_price_min_jpy', sa.Integer()),
        sa.Column('booking_hotel_id', sa.String(200)),
        sa.Column('agoda_hotel_id', sa.String(200)),
        sa.Column('google_rating', sa.Numeric(precision=3, scale=1)),
        sa.Column('booking_score', sa.Numeric(precision=3, scale=1)),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── restaurants ──
    op.create_table('restaurants',
        sa.Column('entity_id', UUID(as_uuid=True), primary_key=True),
        sa.Column('cuisine_type', sa.String(50)),
        sa.Column('sub_cuisine', sa.String(50)),
        sa.Column('michelin_star', sa.SmallInteger()),
        sa.Column('tabelog_score', sa.Numeric(precision=3, scale=2)),
        sa.Column('opening_hours_json', JSONB()),
        sa.Column('seating_count', sa.SmallInteger()),
        sa.Column('requires_reservation', sa.Boolean(), nullable=False),
        sa.Column('reservation_difficulty', sa.String(10)),
        sa.Column('price_range_min_jpy', sa.Integer()),
        sa.Column('price_range_max_jpy', sa.Integer()),
        sa.Column('budget_lunch_jpy', sa.Integer()),
        sa.Column('budget_dinner_jpy', sa.Integer()),
        sa.Column('has_english_menu', sa.Boolean(), nullable=False),
        sa.Column('is_vegetarian_friendly', sa.Boolean(), nullable=False),
        sa.Column('is_halal', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── entity_tags ──
    op.create_table('entity_tags',
        sa.Column('id', sa.BigInteger(), primary_key=True),
        sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('tag_namespace', sa.String(50), nullable=False),
        sa.Column('tag_value', sa.String(100), nullable=False),
        sa.Column('source', sa.String(20)),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── entity_media ──
    op.create_table('entity_media',
        sa.Column('id', sa.BigInteger(), primary_key=True),
        sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('media_type', sa.String(10), nullable=False),
        sa.Column('url', sa.Text(), nullable=False),
        sa.Column('caption_zh', sa.String(500)),
        sa.Column('caption_ja', sa.String(500)),
        sa.Column('sort_order', sa.SmallInteger(), nullable=False),
        sa.Column('is_cover', sa.Boolean(), nullable=False),
        sa.Column('source', sa.String(50)),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── entity_editor_notes ──
    op.create_table('entity_editor_notes',
        sa.Column('id', sa.BigInteger(), primary_key=True),
        sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('note_type', sa.String(30), nullable=False),
        sa.Column('boost_value', sa.SmallInteger()),
        sa.Column('content_zh', sa.Text()),
        sa.Column('content_en', sa.Text()),
        sa.Column('valid_from', sa.DateTime(timezone=True)),
        sa.Column('valid_until', sa.DateTime(timezone=True)),
        sa.Column('created_by', sa.String(100)),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── hotel_area_guide ──
    op.create_table('hotel_area_guide',
        sa.Column('id', sa.BigInteger(), primary_key=True),
        sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('area_summary_zh', sa.Text()),
        sa.Column('nearby_poi_ids', JSONB()),
        sa.Column('transport_tips_zh', sa.Text()),
        sa.Column('walking_distance_station_min', sa.SmallInteger()),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['entity_id'], ['hotels.entity_id']),
    )

    # ── entity_scores ──
    op.create_table('entity_scores',
        sa.Column('score_id', sa.BigInteger(), primary_key=True),
        sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('score_profile', sa.String(50), nullable=False),
        sa.Column('base_score', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('editorial_boost', sa.SmallInteger(), nullable=False),
        sa.Column('final_score', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('score_breakdown', JSONB()),
        sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── orders ──
    op.create_table('orders',
        sa.Column('order_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('user_id', UUID(as_uuid=True)),
        sa.Column('sku_id', sa.String(50), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('amount_cny', sa.Numeric(precision=8, scale=2), nullable=False),
        sa.Column('payment_channel', sa.String(30)),
        sa.Column('payment_tx_id', sa.String(200)),
        sa.Column('paid_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
        sa.ForeignKeyConstraint(['sku_id'], ['product_sku.sku_id']),
    )

    # ── trip_requests ──
    op.create_table('trip_requests',
        sa.Column('trip_request_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('user_id', UUID(as_uuid=True)),
        sa.Column('order_id', UUID(as_uuid=True)),
        sa.Column('sku_id', sa.String(50)),
        sa.Column('raw_input', JSONB(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('last_job_error', sa.Text()),
        sa.Column('retry_count', sa.SmallInteger(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['order_id'], ['orders.order_id']),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id']),
    )

    # ── trip_profiles ──
    op.create_table('trip_profiles',
        sa.Column('profile_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('trip_request_id', UUID(as_uuid=True), nullable=False),
        sa.Column('cities', JSONB(), nullable=False),
        sa.Column('travel_dates', JSONB()),
        sa.Column('duration_days', sa.SmallInteger(), nullable=False),
        sa.Column('party_type', sa.String(30)),
        sa.Column('party_size', sa.SmallInteger()),
        sa.Column('budget_level', sa.String(10)),
        sa.Column('budget_total_cny', sa.Integer()),
        sa.Column('must_have_tags', JSONB(), nullable=False),
        sa.Column('nice_to_have_tags', JSONB(), nullable=False),
        sa.Column('avoid_tags', JSONB(), nullable=False),
        sa.Column('special_requirements', JSONB()),
        sa.Column('normalized_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.trip_request_id']),
    )

    # ── planner_runs ──
    op.create_table('planner_runs',
        sa.Column('planner_run_id', sa.BigInteger(), primary_key=True),
        sa.Column('trip_request_id', UUID(as_uuid=True), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('algorithm_version', sa.String(20)),
        sa.Column('run_params', JSONB()),
        sa.Column('run_log', JSONB()),
        sa.Column('started_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.Column('error_detail', sa.Text()),
        sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.trip_request_id']),
    )

    # ── itinerary_plans ──
    op.create_table('itinerary_plans',
        sa.Column('plan_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('trip_request_id', UUID(as_uuid=True), nullable=False),
        sa.Column('planner_run_id', sa.BigInteger()),
        sa.Column('version', sa.SmallInteger(), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('plan_metadata', JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.trip_request_id']),
        sa.ForeignKeyConstraint(['planner_run_id'], ['planner_runs.planner_run_id']),
    )

    # ── trip_versions ──
    op.create_table('trip_versions',
        sa.Column('version_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('trip_request_id', UUID(as_uuid=True), nullable=False),
        sa.Column('plan_id', UUID(as_uuid=True)),
        sa.Column('version_number', sa.SmallInteger(), nullable=False),
        sa.Column('change_reason', sa.String(200)),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['trip_request_id'], ['trip_requests.trip_request_id']),
        sa.ForeignKeyConstraint(['plan_id'], ['itinerary_plans.plan_id']),
    )

    # ── candidate_sets ──
    op.create_table('candidate_sets',
        sa.Column('candidate_set_id', sa.BigInteger(), primary_key=True),
        sa.Column('planner_run_id', sa.BigInteger(), nullable=False),
        sa.Column('city_code', sa.String(50), nullable=False),
        sa.Column('entity_type', sa.String(20), nullable=False),
        sa.Column('candidate_entity_ids', JSONB(), nullable=False),
        sa.Column('filters_applied', JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['planner_run_id'], ['planner_runs.planner_run_id']),
    )

    # ── itinerary_days ──
    op.create_table('itinerary_days',
        sa.Column('day_id', sa.BigInteger(), primary_key=True),
        sa.Column('plan_id', UUID(as_uuid=True), nullable=False),
        sa.Column('day_number', sa.SmallInteger(), nullable=False),
        sa.Column('date', sa.String(10)),
        sa.Column('city_code', sa.String(50), nullable=False),
        sa.Column('day_theme', sa.String(100)),
        sa.Column('day_summary_zh', sa.Text()),
        sa.Column('hotel_entity_id', UUID(as_uuid=True)),
        sa.Column('estimated_cost_jpy', sa.Integer()),
        sa.ForeignKeyConstraint(['plan_id'], ['itinerary_plans.plan_id']),
        sa.ForeignKeyConstraint(['hotel_entity_id'], ['entity_base.entity_id']),
    )

    # ── itinerary_items ──
    op.create_table('itinerary_items',
        sa.Column('item_id', sa.BigInteger(), primary_key=True),
        sa.Column('day_id', sa.BigInteger(), nullable=False),
        sa.Column('sort_order', sa.SmallInteger(), nullable=False),
        sa.Column('item_type', sa.String(20), nullable=False),
        sa.Column('entity_id', UUID(as_uuid=True)),
        sa.Column('start_time', sa.String(5)),
        sa.Column('end_time', sa.String(5)),
        sa.Column('duration_min', sa.SmallInteger()),
        sa.Column('notes_zh', sa.Text()),
        sa.Column('estimated_cost_jpy', sa.Integer()),
        sa.Column('is_optional', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
        sa.ForeignKeyConstraint(['day_id'], ['itinerary_days.day_id']),
    )

    # ── itinerary_scores ──
    op.create_table('itinerary_scores',
        sa.Column('itinerary_score_id', sa.BigInteger(), primary_key=True),
        sa.Column('plan_id', UUID(as_uuid=True), nullable=False),
        sa.Column('overall_score', sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column('diversity_score', sa.Numeric(precision=5, scale=2)),
        sa.Column('efficiency_score', sa.Numeric(precision=5, scale=2)),
        sa.Column('budget_fit_score', sa.Numeric(precision=5, scale=2)),
        sa.Column('preference_match_score', sa.Numeric(precision=5, scale=2)),
        sa.Column('score_breakdown', JSONB()),
        sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['plan_id'], ['itinerary_plans.plan_id']),
    )

    # ── hotel_offer_snapshots ──
    op.create_table('hotel_offer_snapshots',
        sa.Column('offer_snapshot_id', sa.BigInteger(), primary_key=True),
        sa.Column('entity_id', UUID(as_uuid=True)),
        sa.Column('source_name', sa.String(50), nullable=False),
        sa.Column('check_in_date', sa.String(10), nullable=False),
        sa.Column('check_out_date', sa.String(10), nullable=False),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
        sa.Column('currency', sa.String(3), nullable=False),
        sa.Column('raw_payload', JSONB()),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── hotel_offer_lines ──
    op.create_table('hotel_offer_lines',
        sa.Column('line_id', sa.BigInteger(), primary_key=True),
        sa.Column('offer_snapshot_id', sa.BigInteger(), nullable=False),
        sa.Column('room_type', sa.String(100)),
        sa.Column('bed_type', sa.String(50)),
        sa.Column('price_per_night', sa.Numeric(precision=10, scale=2)),
        sa.Column('total_price', sa.Numeric(precision=10, scale=2)),
        sa.Column('breakfast_included', sa.Boolean(), nullable=False),
        sa.Column('cancellable', sa.Boolean(), nullable=False),
        sa.Column('rooms_available', sa.SmallInteger()),
        sa.Column('booking_url', sa.Text()),
        sa.ForeignKeyConstraint(['offer_snapshot_id'], ['hotel_offer_snapshots.offer_snapshot_id']),
    )

    # ── poi_opening_snapshots ──
    op.create_table('poi_opening_snapshots',
        sa.Column('opening_snapshot_id', sa.BigInteger(), primary_key=True),
        sa.Column('entity_id', UUID(as_uuid=True), nullable=False),
        sa.Column('source_name', sa.String(50), nullable=False),
        sa.Column('check_date', sa.String(10), nullable=False),
        sa.Column('is_open', sa.Boolean()),
        sa.Column('opening_hours_json', JSONB()),
        sa.Column('special_note', sa.Text()),
        sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['entity_id'], ['entity_base.entity_id']),
    )

    # ── export_jobs ──
    op.create_table('export_jobs',
        sa.Column('export_job_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('plan_id', UUID(as_uuid=True), nullable=False),
        sa.Column('render_template_id', sa.BigInteger()),
        sa.Column('export_type', sa.String(20), nullable=False),
        sa.Column('status', sa.String(20), nullable=False),
        sa.Column('error_detail', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.Column('completed_at', sa.DateTime(timezone=True)),
        sa.ForeignKeyConstraint(['plan_id'], ['itinerary_plans.plan_id']),
        sa.ForeignKeyConstraint(['render_template_id'], ['render_templates.render_template_id']),
    )

    # ── export_assets ──
    op.create_table('export_assets',
        sa.Column('asset_id', sa.BigInteger(), primary_key=True),
        sa.Column('export_job_id', UUID(as_uuid=True), nullable=False),
        sa.Column('asset_type', sa.String(20), nullable=False),
        sa.Column('storage_url', sa.Text(), nullable=False),
        sa.Column('file_size_bytes', sa.BigInteger()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['export_job_id'], ['export_jobs.export_job_id']),
    )

    # ── plan_artifacts ──
    op.create_table('plan_artifacts',
        sa.Column('artifact_id', UUID(as_uuid=True), primary_key=True, server_default=sa.text('gen_random_uuid()')),
        sa.Column('plan_id', UUID(as_uuid=True), nullable=False),
        sa.Column('order_id', UUID(as_uuid=True)),
        sa.Column('artifact_type', sa.String(20), nullable=False),
        sa.Column('delivery_url', sa.Text()),
        sa.Column('is_delivered', sa.Boolean(), nullable=False),
        sa.Column('delivered_at', sa.DateTime(timezone=True)),
        sa.Column('download_count', sa.Integer(), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['plan_id'], ['itinerary_plans.plan_id']),
        sa.ForeignKeyConstraint(['order_id'], ['orders.order_id']),
    )

    # ── review_actions ──
    op.create_table('review_actions',
        sa.Column('action_id', sa.BigInteger(), primary_key=True),
        sa.Column('review_job_id', UUID(as_uuid=True), nullable=False),
        sa.Column('action_type', sa.String(30), nullable=False),
        sa.Column('actor', sa.String(100)),
        sa.Column('payload', JSONB()),
        sa.Column('comment', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')),
        sa.ForeignKeyConstraint(['review_job_id'], ['review_jobs.review_job_id']),
    )


def downgrade() -> None:
    # Drop in reverse order to respect FK constraints
    op.drop_table('review_actions')
    op.drop_table('plan_artifacts')
    op.drop_table('export_assets')
    op.drop_table('export_jobs')
    op.drop_table('poi_opening_snapshots')
    op.drop_table('hotel_offer_lines')
    op.drop_table('hotel_offer_snapshots')
    op.drop_table('itinerary_scores')
    op.drop_table('itinerary_items')
    op.drop_table('itinerary_days')
    op.drop_table('candidate_sets')
    op.drop_table('trip_versions')
    op.drop_table('itinerary_plans')
    op.drop_table('planner_runs')
    op.drop_table('trip_profiles')
    op.drop_table('trip_requests')
    op.drop_table('orders')
    op.drop_table('entity_scores')
    op.drop_table('hotel_area_guide')
    op.drop_table('entity_editor_notes')
    op.drop_table('entity_media')
    op.drop_table('entity_tags')
    op.drop_table('restaurants')
    op.drop_table('hotels')
    op.drop_table('pois')
    op.drop_table('review_jobs')
    op.drop_table('route_templates')
    op.drop_table('route_matrix_cache')
    op.drop_table('weather_snapshots')
    op.drop_table('flight_offer_snapshots')
    op.drop_table('source_snapshots')
    op.drop_table('render_templates')
    op.drop_table('entity_base')
    op.drop_table('product_sku')
    op.drop_table('users')
