"""
北海道 S/A 级实体深度数据 seed

包含：
  C1 - 15个核心景点（札幌4 + 函馆3 + 富良野/美瑛3 + 小樽2 + 知床1 + 网走1 + 洞爷湖1）
  C2 - 20家核心餐厅（札幌8 + 函馆5 + 富良野/旭川3 + 小樽2 + 其他2）
  C3 - 8个住宿区域（札幌3 + 函馆2 + 富良野1 + 小樽1 + 知床1）

运行方式：
  python scripts/seed_hokkaido_entities.py

数据来源：Google Maps 评分 / Tabelog / 官方网站 / 实地整理
"""
from __future__ import annotations

import asyncio
import logging
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

logger = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# C1: 景点数据（15个）
# ─────────────────────────────────────────────────────────────────────────────

HOKKAIDO_POIS: list[dict] = [
    # ── 札幌 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "大通公园",
        "name_ja": "大通公園",
        "name_en": "Odori Park",
        "city_code": "sapporo",
        "area_name": "大通",
        "lat": 43.0588,
        "lng": 141.3538,
        "quality_tier": "S",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "morning",
        "visit_duration_min": 60,
        "poi_category": "park",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "all",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.4,
        "google_review_count": 85000,
        "copy_zh": "1.5公里绿轴穿越城市中心，雪祭的冰雕就立在这里，薰衣草花坛在夏天铺满整条街——大通公园是懂得换季的公园，每次来都不一样。",
        "tips_zh": "地铁大通站出来即到，各方向换乘枢纽；2月雪祭主会场",
        "photo_tip": "从电视塔（¥700）顶层俯拍整条公园轴线，夕阳时分最美。冬季雪祭冰雕近拍细节用50mm。",
        "avoid_tip": "雪祭期间（2月初）极度拥挤，建议早晨8点前到场拍空景",
        "nearest_station": "大通駅（地下鉄）",
        "opening_hours": {"weekday": "00:00-23:59"},
    },
    {
        "name_zh": "北海道神宫",
        "name_ja": "北海道神宮",
        "name_en": "Hokkaido Shrine",
        "city_code": "sapporo",
        "area_name": "円山",
        "lat": 43.0565,
        "lng": 141.3215,
        "quality_tier": "S",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "morning",
        "visit_duration_min": 60,
        "poi_category": "shrine",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "spring",
        "crowd_level_typical": "low",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.4,
        "google_review_count": 32000,
        "copy_zh": "北海道最大的神社，藏在円山公园的森林深处。春天神社境内有1400棵染井吉野樱，5月初满开，是当地人最爱的赏樱地，游客极少的宁静版本。",
        "tips_zh": "地铁円山公園站步行15分钟，或円山公园入口步行穿越森林约10分钟",
        "photo_tip": "主殿朱红色建筑配背后雪峰（冬春），或5月满开时神门前樱花框景。",
        "avoid_tip": "元旦三天涌入数十万参拜者，建议绕开1月1-3日",
        "nearest_station": "円山公園駅（地下鉄東西線）",
        "opening_hours": {"weekday": "07:00-17:00", "note": "季节调整，夏季延长至18:00"},
    },
    {
        "name_zh": "羊丘展望台",
        "name_ja": "羊ヶ丘展望台",
        "name_en": "Hitsujigaoka Observation Hill",
        "city_code": "sapporo",
        "area_name": "豊平区",
        "lat": 43.0052,
        "lng": 141.4195,
        "quality_tier": "A",
        "budget_tier": "budget",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "afternoon",
        "visit_duration_min": 60,
        "poi_category": "viewpoint",
        "admission_fee_jpy": 530,
        "admission_free": False,
        "best_season": "summer",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.2,
        "google_review_count": 18000,
        "copy_zh": "「Boys, be ambitious!」——克拉克博士雕像背后是大片牧草地和远处的札幌市区。6-7月绿草如茵，冬天积雪皑皑，是最具北海道气质的一张明信片。",
        "tips_zh": "距市区较远，建议打车或包车前往（约¥2000），公共交通不便",
        "photo_tip": "克拉克博士雕像+背景牧场，夏季绿草地，冬季雪景。顺光拍摄（上午偏西侧，下午偏东侧）。",
        "avoid_tip": "门票略贵，30分钟即可游完，景色虽美但属于「拍完就走」型",
        "nearest_station": "福住駅 → 巴士约15分钟",
        "opening_hours": {"weekday": "09:00-17:00", "summer": "08:30-18:00"},
    },
    {
        "name_zh": "北海道大学银杏大道",
        "name_ja": "北海道大学 イチョウ並木",
        "name_en": "Hokkaido University Ginkgo Avenue",
        "city_code": "sapporo",
        "area_name": "北区",
        "lat": 43.0739,
        "lng": 141.3407,
        "quality_tier": "A",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "afternoon",
        "visit_duration_min": 45,
        "poi_category": "park",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "autumn",
        "crowd_level_typical": "low",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.3,
        "google_review_count": 6000,
        "copy_zh": "380米银杏大道在10月下旬变成整条黄金隧道，落叶铺满地面，散步在里面像走进电影画面——免费、安静、当地人日常的那种美。",
        "tips_zh": "北大正门直走约10分钟到银杏大道，顺带可看农场/牧场，2小时绕行全程",
        "photo_tip": "傍晚逆光拍银杏隧道，落叶黄金色最美。广角15-24mm拍隧道纵深感。",
        "avoid_tip": "10月下旬-11月初最佳，错过则叶落殆尽。夏天普通绿树不值专程前往。",
        "nearest_station": "札幌駅 北口 步行8分钟",
        "opening_hours": {"weekday": "00:00-23:59", "note": "校园免费开放"},
    },
    # ── 函馆 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "函馆山夜景",
        "name_ja": "函館山夜景",
        "name_en": "Mt. Hakodate Night View",
        "city_code": "hakodate",
        "area_name": "函馆山",
        "lat": 41.7596,
        "lng": 140.6955,
        "quality_tier": "S",
        "budget_tier": "budget",
        "booking_method": "walk_in",
        "risk_flags": ["long_queue", "weather_dependent"],
        "best_time_of_day": "night",
        "visit_duration_min": 90,
        "poi_category": "viewpoint",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "all",
        "crowd_level_typical": "high",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 30,
        "google_rating": 4.6,
        "google_review_count": 46000,
        "copy_zh": "全球三大夜景之一。函馆的地形像一根火炬柄，城市灯火从山顶看下去呈完美的沙漏形——这张照片你在其他任何地方拍不到。",
        "tips_zh": "缆车¥1500往返（日落前1小时出发），或步行约40分钟上山（体力好的选项）",
        "photo_tip": "日落后30分钟到完全入夜是黄金拍摄窗口，蓝紫天空配灯火。长焦压缩感强，70-200mm。三脚架必备。",
        "avoid_tip": "缆车旺季排队1小时以上，建议平日傍晚18:30前到；有雾时夜景完全看不到，当天查天气",
        "nearest_station": "函館駅 → 市電「函館ロープウェイ前」步行3分钟",
        "opening_hours": {"weekday": "10:00-22:00", "summer": "10:00-22:00", "winter": "10:00-21:00"},
    },
    {
        "name_zh": "元町西洋建筑群",
        "name_ja": "元町の洋館群",
        "name_en": "Motomachi Historic District",
        "city_code": "hakodate",
        "area_name": "元町",
        "lat": 41.7720,
        "lng": 140.7114,
        "quality_tier": "S",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "morning",
        "visit_duration_min": 120,
        "poi_category": "historic_district",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "all",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.3,
        "google_review_count": 12000,
        "copy_zh": "幕末开港后留下的一整片西洋建筑：旧英国领事馆、东正教堂、公会堂……函馆的异国感是真实历史堆出来的，不是装出来的。",
        "tips_zh": "二十间坂/八幡坂是最有代表性的坡道，从元町散步到函馆山山脚约30分钟",
        "photo_tip": "八幡坂正面拍：坡道尽头是函馆港的海面，晴天逆光构图极美。早上8点前游客少，光线柔和。",
        "avoid_tip": "各洋馆室内参观票价¥200-300，外观免费，不感兴趣内部陈列可不购票",
        "nearest_station": "函館駅 → 市電「末広町」步行5分钟",
        "opening_hours": {"weekday": "00:00-23:59", "note": "街区免费游览，各建筑内部有独立开放时间"},
    },
    {
        "name_zh": "五棱郭",
        "name_ja": "五稜郭",
        "name_en": "Goryokaku Fort",
        "city_code": "hakodate",
        "area_name": "五棱郭",
        "lat": 41.7961,
        "lng": 140.7565,
        "quality_tier": "S",
        "budget_tier": "budget",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "morning",
        "visit_duration_min": 90,
        "poi_category": "historic_site",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "spring",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.4,
        "google_review_count": 29000,
        "copy_zh": "日本唯一的五角星形城堡，从五棱郭塔（¥900）俯瞰时五角形轮廓完整清晰。春天1600株樱花沿护城河盛开，从高处看像粉色五芒星。",
        "tips_zh": "五棱郭塔是俯瞰必去，城堡内部免费游览",
        "photo_tip": "五棱郭塔展望台俯拍五角星全貌，春天粉色+绿色形状最美。地面可沿护城河边漫步拍细节。",
        "avoid_tip": "五月初樱花季人极多，平日早晨或傍晚相对清静",
        "nearest_station": "市電「五稜郭公園前」步行15分钟",
        "opening_hours": {"weekday": "05:00-19:00", "winter": "05:00-18:00"},
    },
    # ── 富良野 / 美瑛 ─────────────────────────────────────────────────────────
    {
        "name_zh": "富田农场",
        "name_ja": "ファーム富田",
        "name_en": "Farm Tomita",
        "city_code": "furano",
        "area_name": "中富良野",
        "lat": 43.5497,
        "lng": 142.4724,
        "quality_tier": "S",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": ["seasonal"],
        "best_time_of_day": "morning",
        "visit_duration_min": 90,
        "poi_category": "farm",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "summer",
        "crowd_level_typical": "high",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.5,
        "google_review_count": 38000,
        "copy_zh": "北海道最具代表性的薰衣草农场，7月的紫色花田连到天边，薰衣草冰淇淋是必吃——这张明信片你认出来，是因为它就在这里拍的。",
        "tips_zh": "薰衣草盛花期为7月上中旬，6月下旬和7月下旬部分区域仍有花。全年免费入场，礼品店/食堂区域消费。",
        "photo_tip": "彩虹花田（紫/黄/橙/红平行条纹）是最佳拍摄点，上午侧光色彩饱和。无人机禁飞，只能地面拍。",
        "avoid_tip": "7月中旬每天游客数千，停车场早上9点后基本满，建议8点前到或搭乘ラベンダー号观光列车",
        "nearest_station": "中富良野駅 → 步行15分钟 / 旺季有ラベンダー号直达",
        "opening_hours": {"summer": "08:30-17:00", "note": "花期外时间缩短，1-3月部分关闭"},
    },
    {
        "name_zh": "美瑛拼布之路",
        "name_ja": "美瑛 パッチワークの路",
        "name_en": "Biei Patchwork Road",
        "city_code": "furano",
        "area_name": "美瑛",
        "lat": 43.5875,
        "lng": 142.4709,
        "quality_tier": "S",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "morning",
        "visit_duration_min": 120,
        "poi_category": "scenic_road",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "summer",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.4,
        "google_review_count": 14000,
        "copy_zh": "起伏丘陵上不同颜色的农田拼在一起像一块大被子，开车绕行是享受——「哲学树」「セブンスターの木」就散落在路边，随时可以停车发呆。",
        "tips_zh": "自驾最便利（旭川机场租车后直接开往美瑛），美瑛站有租自行车¥800/日",
        "photo_tip": "「クリスマスツリーの木」孤独白桦配丘陵背景，清晨薄雾最美。广角镜头拍农田色块层次。",
        "avoid_tip": "部分有名的「树」在私人农田内，不要踏入农地。冬季积雪期道路部分关闭。",
        "nearest_station": "美瑛駅 → 自行车/出租车",
        "opening_hours": {"weekday": "00:00-23:59", "note": "道路全年开放，部分景点冬季封闭"},
    },
    {
        "name_zh": "青池（白金青い池）",
        "name_ja": "白金青い池",
        "name_en": "Blue Pond Shirogane",
        "city_code": "furano",
        "area_name": "美瑛・白金",
        "lat": 43.5282,
        "lng": 142.5600,
        "quality_tier": "S",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": ["weather_dependent"],
        "best_time_of_day": "morning",
        "visit_duration_min": 45,
        "poi_category": "natural_scenery",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "all",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.5,
        "google_review_count": 25000,
        "copy_zh": "苹果公司曾将这里的照片设为 Mac 壁纸。铝成分让水呈现奇异的蓝绿色，枯立的白桦树倒映水中——晴天上午10点前光线最干净，浊色最蓝。",
        "tips_zh": "距美瑛站开车约20分钟，无公共交通，需自驾或参加一日游团",
        "photo_tip": "广角拍全景，倒影需无风天气。冬天夜间有灯光照射（16:00-21:30），蓝色更深邃。",
        "avoid_tip": "雨后或强风时水面浑浊，蓝色消失；晴天早上颜色最纯净",
        "nearest_station": "美瑛駅 → 自驾20分钟",
        "opening_hours": {"weekday": "00:00-23:59", "note": "停车场¥200"},
    },
    # ── 小樽 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "小樽运河",
        "name_ja": "小樽運河",
        "name_en": "Otaru Canal",
        "city_code": "otaru",
        "area_name": "小樽中心",
        "lat": 43.1946,
        "lng": 140.9908,
        "quality_tier": "S",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "night",
        "visit_duration_min": 90,
        "poi_category": "landmark",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "all",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.4,
        "google_review_count": 52000,
        "copy_zh": "明治末期繁华商港的遗迹，石仓库群倒映在运河中，夜晚煤气灯点亮整条水道——是那种「比想象中更好看」的地方，冬天积雪时更梦幻。",
        "tips_zh": "从小樽站步行10分钟，运河沿线有煤气灯约63盏，日落后30分钟全部亮起",
        "photo_tip": "南端浅草橋是最经典机位，倒映+灯光。冬天雪景+灯光是全年最美时刻，早到可拍蓝调时刻。",
        "avoid_tip": "运河沿线餐厅价格偏贵，建议走进内街找当地居酒屋",
        "nearest_station": "小樽駅 步行10分钟",
        "opening_hours": {"weekday": "00:00-23:59"},
    },
    {
        "name_zh": "堺町通（北一硝子）",
        "name_ja": "堺町通り・北一ガラス",
        "name_en": "Sakaimachi Street - Kitaichi Glass",
        "city_code": "otaru",
        "area_name": "堺町",
        "lat": 43.1919,
        "lng": 140.9926,
        "quality_tier": "A",
        "budget_tier": "mid",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "afternoon",
        "visit_duration_min": 90,
        "poi_category": "shopping_district",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "all",
        "crowd_level_typical": "medium",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.2,
        "google_review_count": 9000,
        "copy_zh": "小樽玻璃工艺的发源地，北一硝子用168盏煤油灯照亮整个店堂，手工玻璃器皿是最有质感的小樽伴手礼。配上小樽洋菓子的LeTAO双层芝士蛋糕。",
        "tips_zh": "北一硝子三号馆内部免费参观，无需消费；LeTAO本店在附近，堂食双层芝士必点",
        "photo_tip": "北一硝子三号馆内煤油灯+玻璃器皿，暖光氛围感极强，竖构图。",
        "avoid_tip": "周末下午游客密集，堺町通徒步进去才是正确打开方式，不要坐人力车（价格贵且无必要）",
        "nearest_station": "小樽駅 步行15分钟",
        "opening_hours": {"weekday": "08:45-18:00"},
    },
    # ── 知床 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "知床五湖",
        "name_ja": "知床五湖",
        "name_en": "Shiretoko Five Lakes",
        "city_code": "abashiri",
        "area_name": "知床",
        "lat": 44.0726,
        "lng": 145.1010,
        "quality_tier": "S",
        "budget_tier": "budget",
        "booking_method": "advance_booking",
        "risk_flags": ["requires_guide", "seasonal", "bear_warning"],
        "best_time_of_day": "morning",
        "visit_duration_min": 150,
        "poi_category": "natural_scenery",
        "admission_fee_jpy": 250,
        "admission_free": False,
        "best_season": "summer",
        "crowd_level_typical": "medium",
        "requires_advance_booking": True,
        "advance_booking_days": 14,
        "queue_wait_typical_min": 0,
        "google_rating": 4.6,
        "google_review_count": 17000,
        "copy_zh": "世界自然遗产，五个原始湖泊倒映知床连山——这里是棕熊的领地，植被原始到感觉时间停滞。早晨湖面无风时的倒影是北海道最震撼的自然景观之一。",
        "tips_zh": "5-7月熊出没活跃期需跟随持证向导（需预约）；8月后可部分自由行走。高架木道区域免费，地上散策须付导览费约¥5000",
        "photo_tip": "一湖倒影+知床连山，无风晴天早上8点前光线最好。广角16-24mm。",
        "avoid_tip": "绝对不要单独进入森林；棕熊遭遇时不要奔跑，随身携带熊铃",
        "nearest_station": "ウトロ温泉バスターミナル → 巴士约20分钟",
        "opening_hours": {"summer": "07:30-18:30", "note": "5月中旬-10月下旬开放，冬季关闭"},
    },
    # ── 网走 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "网走流冰（破冰船体验）",
        "name_ja": "流氷（砕氷船おーろら）",
        "name_en": "Drift Ice - Aurora Icebreaker",
        "city_code": "abashiri",
        "area_name": "网走",
        "lat": 44.0191,
        "lng": 144.2736,
        "quality_tier": "S",
        "budget_tier": "mid",
        "booking_method": "advance_booking",
        "risk_flags": ["seasonal", "weather_dependent"],
        "best_time_of_day": "morning",
        "visit_duration_min": 60,
        "poi_category": "experience",
        "admission_fee_jpy": 4000,
        "admission_free": False,
        "best_season": "winter",
        "crowd_level_typical": "high",
        "requires_advance_booking": True,
        "advance_booking_days": 21,
        "queue_wait_typical_min": 0,
        "google_rating": 4.5,
        "google_review_count": 8000,
        "copy_zh": "每年2月，鄂霍次克海结冰，破冰船切开白色浮冰驶向远方——站在甲板上看冰面开裂的声音和画面，是北海道独一无二的体验，地球上没有多少地方能看到这个。",
        "tips_zh": "「砕氷船おーろら」运营时间约2月1日-3月下旬，1日2-3班，每班约1小时。需提前2-3周在官网或Klook预订。",
        "photo_tip": "船头甲板位置最佳，俯拍冰面裂开瞬间。日出前后光线金红色，与冰面形成强对比。长焦400mm以上拍远处流冰纹理。",
        "avoid_tip": "流冰量因年而异，大年份壮观、小年份薄弱；出发前查当年流冰预报（网走市观光协会）",
        "nearest_station": "网走站步行10分钟至乘船码头",
        "opening_hours": {"winter": "2月1日-3月下旬 08:00/11:00/14:00 各班"},
    },
    # ── 洞爷湖 ────────────────────────────────────────────────────────────────
    {
        "name_zh": "洞爷湖",
        "name_ja": "洞爺湖",
        "name_en": "Lake Toya",
        "city_code": "toya",
        "area_name": "洞爷湖",
        "lat": 42.6018,
        "lng": 140.7776,
        "quality_tier": "A",
        "budget_tier": "free",
        "booking_method": "walk_in",
        "risk_flags": [],
        "best_time_of_day": "morning",
        "visit_duration_min": 120,
        "poi_category": "lake",
        "admission_fee_jpy": 0,
        "admission_free": True,
        "best_season": "summer",
        "crowd_level_typical": "low",
        "requires_advance_booking": False,
        "queue_wait_typical_min": 0,
        "google_rating": 4.4,
        "google_review_count": 11000,
        "copy_zh": "平静如镜的火山口湖，湖中有中岛，周边温泉旅馆在湖边一字排开——这里是减速度过的地方，不是打卡的地方。泡完温泉对着湖吃完早餐就是最好的一天。",
        "tips_zh": "距札幌约2小时车程，适合作为1晚温泉住宿中转地；夏季有湖上游船¥1500",
        "photo_tip": "清晨湖面无风时拍倒影+羊蹄山（晴天），或傍晚夕阳映湖。",
        "avoid_tip": "洞爷湖镇本身较小，游览不超过半天；主要体验是住一晚温泉旅馆",
        "nearest_station": "洞爺駅 → 巴士20分钟到湖畔",
        "opening_hours": {"weekday": "00:00-23:59"},
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# C2: 餐厅数据（20家）
# ─────────────────────────────────────────────────────────────────────────────

HOKKAIDO_RESTAURANTS: list[dict] = [
    # ── 札幌 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "汤咖喱 Suage+（札幌总店）",
        "name_ja": "スープカレー Suage+",
        "name_en": "Soup Curry Suage+",
        "city_code": "sapporo",
        "area_name": "大通",
        "lat": 43.0604,
        "lng": 141.3497,
        "quality_tier": "S",
        "budget_tier": "mid",
        "cuisine_type": "soup_curry",
        "tabelog_score": 3.81,
        "michelin_star": 0,
        "price_range_min_jpy": 1000,
        "price_range_max_jpy": 2000,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": ["long_queue"],
        "copy_zh": "札幌最有名的汤咖喱之一，浓郁椰奶咖喱汤底配整块软烂鸡腿，辣度可自选——在北海道不吃一碗汤咖喱等于没来过。",
        "tips_zh": "11点刚开门人少，12点后常排队；辣度从0（无辣）到10自选",
        "avoid_tip": "分量够大，不建议点最大份",
        "nearest_station": "大通駅 步行5分钟",
        "opening_hours": {"weekday": "11:00-22:00"},
    },
    {
        "name_zh": "蟹本家（かに本家）",
        "name_ja": "かに本家",
        "name_en": "Kani Honke",
        "city_code": "sapporo",
        "area_name": "薄野",
        "lat": 43.0549,
        "lng": 141.3559,
        "quality_tier": "S",
        "budget_tier": "premium",
        "cuisine_type": "seafood_crab",
        "tabelog_score": 3.82,
        "michelin_star": 0,
        "price_range_min_jpy": 8000,
        "price_range_max_jpy": 20000,
        "requires_reservation": True,
        "reservation_difficulty": "medium",
        "has_english_menu": True,
        "booking_method": "reservation",
        "risk_flags": [],
        "copy_zh": "北海道螃蟹料理老铺，毛蟹/帝王蟹/花咲蟹三种本道蟹齐全，套餐从蒸蟹到蟹刺身一条龙——在这里吃一顿是给北海道海鲜之旅画一个完整的句号。",
        "tips_zh": "建议提前3-7天预约，套餐¥8000-15000，单人也可以坐吧台点单品蟹肉",
        "avoid_tip": "价格较高，确认好菜单价格再入座",
        "nearest_station": "薄野駅 步行3分钟",
        "opening_hours": {"weekday": "11:30-22:00"},
    },
    {
        "name_zh": "成吉思汗（松尾ジンギスカン 札幌本店）",
        "name_ja": "松尾ジンギスカン 札幌店",
        "name_en": "Matsuo Jingisukan",
        "city_code": "sapporo",
        "area_name": "狸小路",
        "lat": 43.0572,
        "lng": 141.3540,
        "quality_tier": "S",
        "budget_tier": "mid",
        "cuisine_type": "jingisukan_bbq",
        "tabelog_score": 3.68,
        "michelin_star": 0,
        "price_range_min_jpy": 2000,
        "price_range_max_jpy": 4000,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "成吉思汗烤肉是北海道最代表性的饮食文化，松尾家的秘制酱汁羊肉在北海道人心中地位等同于关西人对章鱼烧的感情——配生啤是标配。",
        "tips_zh": "平日晚上直接进，周末可能等位20分钟；酱汁版比蘸汁版更适合初次尝试",
        "avoid_tip": "用餐后衣服会有烤肉味，安排好后续行程",
        "nearest_station": "薄野駅/大通駅 步行5分钟",
        "opening_hours": {"weekday": "11:00-23:00"},
    },
    {
        "name_zh": "回转寿司 根室花まる（ESTA店）",
        "name_ja": "回転寿し 根室花まる",
        "name_en": "Nemuro Hanamaru Rotating Sushi",
        "city_code": "sapporo",
        "area_name": "札幌站",
        "lat": 43.0688,
        "lng": 141.3507,
        "quality_tier": "S",
        "budget_tier": "mid",
        "cuisine_type": "sushi_kaiten",
        "tabelog_score": 3.88,
        "michelin_star": 0,
        "price_range_min_jpy": 1500,
        "price_range_max_jpy": 3500,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": ["long_queue"],
        "copy_zh": "北海道最好的回转寿司，扇贝/海胆/帝王蟹脚/生鲑鱼肥厚到可以用来量厚度——¥220一盘的价格配北海道顶级食材，这就是在产地吃海鲜的意义。",
        "tips_zh": "开店（11:00）前30分钟取整理券，否则排队1小时以上；ESTA店（札幌站旁）最方便",
        "avoid_tip": "现场不接受预约，只能靠早到排队",
        "nearest_station": "札幌駅 步行3分钟（ESTA 6F）",
        "opening_hours": {"weekday": "11:00-22:00"},
    },
    {
        "name_zh": "拉面共和国（ラーメン共和国）",
        "name_ja": "ラーメン共和国",
        "name_en": "Ramen Kyowakoku",
        "city_code": "sapporo",
        "area_name": "札幌站",
        "lat": 43.0685,
        "lng": 141.3512,
        "quality_tier": "A",
        "budget_tier": "budget",
        "cuisine_type": "ramen",
        "tabelog_score": 3.50,
        "michelin_star": 0,
        "price_range_min_jpy": 900,
        "price_range_max_jpy": 1500,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "集合了8家北海道名拉面店的美食主题楼层，味噌/盐味/酱油三种北海道派系各有代表店，换一家吃一碗是最快了解北海道拉面全貌的方式。",
        "tips_zh": "在ESTA 10F，每家都可以单独用餐；午餐11-14点相对人少",
        "avoid_tip": "各家味道差异明显，不妨先查Tabelog评分再选",
        "nearest_station": "札幌駅（ESTA 10F）",
        "opening_hours": {"weekday": "11:00-22:00"},
    },
    {
        "name_zh": "すし善（寿司善）总本店",
        "name_ja": "すし善",
        "name_en": "Sushizen",
        "city_code": "sapporo",
        "area_name": "大通",
        "lat": 43.0594,
        "lng": 141.3518,
        "quality_tier": "A",
        "budget_tier": "premium",
        "cuisine_type": "sushi_kappo",
        "tabelog_score": 3.93,
        "michelin_star": 1,
        "price_range_min_jpy": 15000,
        "price_range_max_jpy": 30000,
        "requires_reservation": True,
        "reservation_difficulty": "hard",
        "has_english_menu": False,
        "booking_method": "reservation",
        "risk_flags": ["reservation_required"],
        "copy_zh": "米其林一星，北海道产时令食材驱动的正统江户前寿司，主厨出身东京修业。想在北海道吃一顿记得住的寿司怀石，这是答案之一。",
        "tips_zh": "需电话或官网提前2-4周预约，晚市套餐¥20000起，午市相对经济",
        "avoid_tip": "全日文菜单，无英文服务，需有一定日文基础或请酒店前台代订",
        "nearest_station": "大通駅 步行3分钟",
        "opening_hours": {"weekday": "11:30-14:00 / 17:30-22:00", "closed": "不定休"},
    },
    {
        "name_zh": "北海道农家汤咖喱 Rojiura Curry SAMURAI.",
        "name_ja": "Rojiura Curry SAMURAI.",
        "name_en": "Rojiura Curry Samurai",
        "city_code": "sapporo",
        "area_name": "円山",
        "lat": 43.0568,
        "lng": 141.3233,
        "quality_tier": "A",
        "budget_tier": "mid",
        "cuisine_type": "soup_curry",
        "tabelog_score": 3.78,
        "michelin_star": 0,
        "price_range_min_jpy": 1200,
        "price_range_max_jpy": 2200,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "使用北海道当地蔬菜的「农家风」汤咖喱，蔬菜量惊人，鸡腿肉软烂脱骨，汤底带有微甜椰奶香——另一个版本的北海道味道。",
        "tips_zh": "円山公园附近，周末下午1-2点人最多，早去或晚去",
        "avoid_tip": "分量很大，不建议加大份",
        "nearest_station": "円山公園駅 步行10分钟",
        "opening_hours": {"weekday": "11:30-21:00", "closed": "周二"},
    },
    {
        "name_zh": "炉端焼き 炉ばた（薄野）",
        "name_ja": "炉ばた",
        "name_en": "Robata Grill Robata",
        "city_code": "sapporo",
        "area_name": "薄野",
        "lat": 43.0545,
        "lng": 141.3548,
        "quality_tier": "A",
        "budget_tier": "mid",
        "cuisine_type": "robatayaki",
        "tabelog_score": 3.62,
        "michelin_star": 0,
        "price_range_min_jpy": 3000,
        "price_range_max_jpy": 6000,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": False,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "老式炉端烤风格，面对炭火炉，眼前是当天进的北海道海鲜和蔬菜，用长叉递给你——这是吃法最古朴也最有参与感的北海道居酒屋体验。",
        "tips_zh": "薄野夜生活区，晚18点后热闹，日语点餐为主，指着食材说「これ（kore）」即可",
        "avoid_tip": "完全无英文菜单，适合有点探险精神的食客",
        "nearest_station": "薄野駅 步行5分钟",
        "opening_hours": {"weekday": "17:00-23:30", "closed": "周日"},
    },
    # ── 函馆 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "函馆朝市（鸡二郎）",
        "name_ja": "函館朝市 どんぶり横丁",
        "name_en": "Hakodate Morning Market - Donburi Yokocho",
        "city_code": "hakodate",
        "area_name": "函馆站前",
        "lat": 41.7745,
        "lng": 140.7290,
        "quality_tier": "S",
        "budget_tier": "mid",
        "cuisine_type": "seafood_bowl",
        "tabelog_score": 3.72,
        "michelin_star": 0,
        "price_range_min_jpy": 1500,
        "price_range_max_jpy": 3500,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "早上6点开门的海鲜市场，「巴丼（巴丼）」装着函馆三宝：鲜鱿鱼/海胆/帝王蟹，从捕捞到盛碗不超过一天——这是函馆的时间标准，全年最对的一顿早餐。",
        "tips_zh": "6-9点是朝市最活跃时段；鸡二郎（函馆朝市どんぶり横丁内）排队但值得",
        "avoid_tip": "11点后部分摊位开始收摊，建议上午早去",
        "nearest_station": "函館駅 步行3分钟",
        "opening_hours": {"weekday": "06:00-14:00", "winter": "07:00-13:00"},
    },
    {
        "name_zh": "函馆盐味拉面 あじさい",
        "name_ja": "函館麺厨房 あじさい",
        "name_en": "Ajisai Hakodate Salt Ramen",
        "city_code": "hakodate",
        "area_name": "五棱郭",
        "lat": 41.7960,
        "lng": 140.7570,
        "quality_tier": "S",
        "budget_tier": "budget",
        "cuisine_type": "ramen_shio",
        "tabelog_score": 3.82,
        "michelin_star": 0,
        "price_range_min_jpy": 900,
        "price_range_max_jpy": 1400,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": ["long_queue"],
        "copy_zh": "函馆是盐味拉面的发源地，あじさい的透明金黄色汤底是50多年的配方——清澈不油腻，海鲜鲜味在每一口汤里，是那种喝完想再来一碗的温柔。",
        "tips_zh": "五棱郭本店，游完五棱郭后步行即到，11-13点排队较多",
        "avoid_tip": "名气大，节假日等位30-40分钟，提早到",
        "nearest_station": "市電「五稜郭公園前」步行10分钟",
        "opening_hours": {"weekday": "11:00-20:30", "closed": "周三"},
    },
    {
        "name_zh": "彩や（函馆创意海鲜）",
        "name_ja": "彩や",
        "name_en": "Irodoriya",
        "city_code": "hakodate",
        "area_name": "湯の川",
        "lat": 41.7875,
        "lng": 140.7581,
        "quality_tier": "A",
        "budget_tier": "mid",
        "cuisine_type": "seafood_izakaya",
        "tabelog_score": 3.75,
        "michelin_star": 0,
        "price_range_min_jpy": 3000,
        "price_range_max_jpy": 7000,
        "requires_reservation": True,
        "reservation_difficulty": "medium",
        "has_english_menu": False,
        "booking_method": "reservation",
        "risk_flags": [],
        "copy_zh": "函馆本地人晚餐首选，当天进的津轻海峡鲜鱼配自酿地酒，日式小菜精致——这种「当地人才知道」的居酒屋，比函馆山更值得记住。",
        "tips_zh": "建议提前一天电话预约，湯の川温泉旅馆区附近，晚餐后步行回旅馆正好",
        "avoid_tip": "全日文点餐，指着菜单或请旅馆前台帮助确认",
        "nearest_station": "市電「湯の川」步行5分钟",
        "opening_hours": {"weekday": "17:00-23:00", "closed": "周日"},
    },
    {
        "name_zh": "Café テトラポット（函馆咖啡）",
        "name_ja": "Café テトラポット",
        "name_en": "Cafe Tetrapot",
        "city_code": "hakodate",
        "area_name": "元町",
        "lat": 41.7718,
        "lng": 140.7108,
        "quality_tier": "A",
        "budget_tier": "budget",
        "cuisine_type": "cafe",
        "tabelog_score": 3.55,
        "michelin_star": 0,
        "price_range_min_jpy": 600,
        "price_range_max_jpy": 1200,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "元町坡道上的老洋馆改造咖啡馆，坐在窗边可以看到函馆湾——逛完元町后在这里一杯咖啡，把风景留在眼里，是函馆最好的散步收尾。",
        "tips_zh": "窗边座位有限，工作日下午来最有机会坐到；有无麸质蛋糕",
        "avoid_tip": "周末下午座位紧张，有等待心理准备",
        "nearest_station": "市電「末広町」步行8分钟",
        "opening_hours": {"weekday": "10:00-18:00", "closed": "周二"},
    },
    {
        "name_zh": "Lucky Pierrot（函馆本地汉堡）",
        "name_ja": "ラッキーピエロ",
        "name_en": "Lucky Pierrot",
        "city_code": "hakodate",
        "area_name": "函馆市内",
        "lat": 41.7734,
        "lng": 140.7288,
        "quality_tier": "A",
        "budget_tier": "budget",
        "cuisine_type": "burger",
        "tabelog_score": 3.55,
        "michelin_star": 0,
        "price_range_min_jpy": 500,
        "price_range_max_jpy": 1000,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "函馆限定的本地汉堡连锁，炸鸡汉堡是头牌，不会比你吃过的任何连锁汉堡更精致，但它是函馆人日常生活的一部分——只在函馆吃得到，这就够了。",
        "tips_zh": "函馆市内17家门店，朝市附近店最方便；代表作「チャイニーズチキンバーガー」",
        "avoid_tip": "口味普通，不要抱太高期待，吃的是体验",
        "nearest_station": "函馆市内各处均有门店",
        "opening_hours": {"weekday": "10:00-23:00"},
    },
    # ── 富良野 / 旭川 ─────────────────────────────────────────────────────────
    {
        "name_zh": "富良野葡萄酒酿造场（餐厅）",
        "name_ja": "富良野ワイン工場 レストラン",
        "name_en": "Furano Wine Restaurant",
        "city_code": "furano",
        "area_name": "富良野",
        "lat": 43.3374,
        "lng": 142.3841,
        "quality_tier": "A",
        "budget_tier": "mid",
        "cuisine_type": "wine_dining",
        "tabelog_score": 3.60,
        "michelin_star": 0,
        "price_range_min_jpy": 2000,
        "price_range_max_jpy": 5000,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "富良野产葡萄酒配当地牧场奶酪和香肠，在葡萄园中用餐，窗外就是薰衣草丘陵——这一顿不是奢华，但它是北海道最「产地感」的一餐。",
        "tips_zh": "酒庄参观免费，餐厅午市11-14点，不需要预约",
        "avoid_tip": "7-8月旺季午餐时段满座较快，11点前到",
        "nearest_station": "富良野駅 → 出租车约10分钟",
        "opening_hours": {"weekday": "11:00-16:00", "closed": "周一"},
    },
    {
        "name_zh": "旭川拉面 蜂屋（本店）",
        "name_ja": "旭川ラーメン 蜂屋",
        "name_en": "Ramen Hachitatsu Asahikawa",
        "city_code": "furano",
        "area_name": "旭川",
        "lat": 43.7706,
        "lng": 142.3617,
        "quality_tier": "S",
        "budget_tier": "budget",
        "cuisine_type": "ramen_asahikawa",
        "tabelog_score": 3.89,
        "michelin_star": 0,
        "price_range_min_jpy": 800,
        "price_range_max_jpy": 1300,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": False,
        "booking_method": "walk_in",
        "risk_flags": ["long_queue"],
        "copy_zh": "旭川系拉面的代名词，豚骨+鱼介双汤底配背脂，冬天喝下去从胃暖到脚尖——旭川的气温比札幌低5度，这碗拉面是当地人活下去的理由。",
        "tips_zh": "昭和老铺，1947年创业；午餐11-13点排队30-60分钟，早到",
        "avoid_tip": "现金现场点餐，全日文菜单，指「ラーメン（ramen）」即是招牌",
        "nearest_station": "旭川駅 步行10分钟",
        "opening_hours": {"weekday": "10:30-20:30", "closed": "周三"},
    },
    {
        "name_zh": "新大雪旅馆（温泉旅馆晚膳）",
        "name_ja": "旭岳温泉 大雪山白雲荘",
        "name_en": "Daisetsuzan Shirakumo-so",
        "city_code": "furano",
        "area_name": "大雪山旭岳",
        "lat": 43.6642,
        "lng": 142.8549,
        "quality_tier": "A",
        "budget_tier": "mid",
        "cuisine_type": "kaiseki_mountain",
        "tabelog_score": 0,
        "michelin_star": 0,
        "price_range_min_jpy": 3000,
        "price_range_max_jpy": 6000,
        "requires_reservation": True,
        "reservation_difficulty": "medium",
        "has_english_menu": False,
        "booking_method": "reservation",
        "risk_flags": ["seasonal"],
        "copy_zh": "旭岳温泉山脚唯一的公共山小屋，北海道山野食材做成的朴素晚膳，泡完温泉对着大雪山吃饭——海拔1100米的用餐，食材不精致但氛围是无价的。",
        "tips_zh": "需住宿才能用晚餐，提前官网预约；仅6-10月开放（积雪期关闭）",
        "avoid_tip": "这里的价值在「在哪里吃」而非「吃什么」，非住客不提供单独餐饮",
        "nearest_station": "旭川駅 → 巴士约2小时",
        "opening_hours": {"summer": "仅6-10月开放"},
    },
    # ── 小樽 ──────────────────────────────────────────────────────────────────
    {
        "name_zh": "鱗友朝市（小樽）",
        "name_ja": "鱗友朝市",
        "name_en": "Rinyu Morning Market",
        "city_code": "otaru",
        "area_name": "小樽港",
        "lat": 43.1973,
        "lng": 140.9979,
        "quality_tier": "A",
        "budget_tier": "budget",
        "cuisine_type": "seafood_market",
        "tabelog_score": 3.58,
        "michelin_star": 0,
        "price_range_min_jpy": 800,
        "price_range_max_jpy": 2000,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": False,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "小樽本地人的朝市，比光顾游客的「三角市场」更真实——摊主就是出海捕鱼的渔夫，鱼的新鲜程度用「几点捞上来」来衡量。",
        "tips_zh": "早上6-9点是营业高峰，9点后陆续收摊；现金为主",
        "avoid_tip": "不是观光市场，没有服务性引导，需自己找到摊位点",
        "nearest_station": "小樽駅 步行15分钟（近港口）",
        "opening_hours": {"weekday": "05:00-12:00"},
    },
    {
        "name_zh": "LeTAO 本店（小樽）",
        "name_ja": "LeTAO 本店",
        "name_en": "LeTAO Patisserie",
        "city_code": "otaru",
        "area_name": "堺町",
        "lat": 43.1924,
        "lng": 140.9935,
        "quality_tier": "S",
        "budget_tier": "mid",
        "cuisine_type": "patisserie",
        "tabelog_score": 3.74,
        "michelin_star": 0,
        "price_range_min_jpy": 500,
        "price_range_max_jpy": 2500,
        "requires_reservation": False,
        "reservation_difficulty": "none",
        "has_english_menu": True,
        "booking_method": "walk_in",
        "risk_flags": [],
        "copy_zh": "北海道最知名的洋菓子品牌，总本店就在小樽堺町通，「ドゥーブルフロマージュ（双层芝士蛋糕）」层次分明绵密轻盈——这块蛋糕是北海道乳制品品质最直接的证明。",
        "tips_zh": "本店2楼有堂食，可点双层芝士蛋糕+红茶；伴手礼在1楼购买，保存期有限，提前算好携带天数",
        "avoid_tip": "双层芝士需冷藏，不适合放在行李箱超过8小时，购买时间安排在回程前",
        "nearest_station": "小樽駅 步行15分钟",
        "opening_hours": {"weekday": "09:00-18:00"},
    },
    {
        "name_zh": "海鲜丼 おたる政寿司",
        "name_ja": "おたる政寿司",
        "name_en": "Otaru Masazushi",
        "city_code": "otaru",
        "area_name": "小樽中心",
        "lat": 43.1904,
        "lng": 140.9944,
        "quality_tier": "A",
        "budget_tier": "premium",
        "cuisine_type": "sushi",
        "tabelog_score": 3.80,
        "michelin_star": 0,
        "price_range_min_jpy": 3000,
        "price_range_max_jpy": 12000,
        "requires_reservation": True,
        "reservation_difficulty": "medium",
        "has_english_menu": True,
        "booking_method": "reservation",
        "risk_flags": [],
        "copy_zh": "小樽寿司屋通最老字号之一，鲑鱼/海胆/帝王蟹产地直送，握寿司每一贯都看得出认真——想在小樽吃一顿正经寿司，选这里不会错。",
        "tips_zh": "建议提前1-2天电话预约，午市性价比高；吧台座位可看师傅握寿司",
        "avoid_tip": "价格不低，确认好预算再入座",
        "nearest_station": "小樽駅 步行10分钟",
        "opening_hours": {"weekday": "11:30-21:00", "closed": "周四"},
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# C3: 住宿区域数据（8个）
# ─────────────────────────────────────────────────────────────────────────────

HOKKAIDO_HOTEL_AREAS: list[dict] = [
    # ── 札幌 ──────────────────────────────────────────────────────────────────
    {
        "area_name": "札幌站・大通周边",
        "city_code": "sapporo",
        "description_zh": (
            "交通最便利的核心区，步行连接JR札幌站、地铁大通站、狸小路商圈。"
            "高中低档酒店选择最多，商务出行+观光双用途最佳选择。"
            "周边遍布便利店、药妆、百货（大丸/エスタ），夜间购物到23点不成问题。"
        ),
        "typical_price_range": "¥8000-25000/晚（按档次差异大）",
        "recommended_for": ["商务+观光双用途", "行李多/频繁换车者", "第一次来北海道"],
        "walking_highlights": ["狸小路商圈（2分钟）", "大通公园（10分钟）", "时计台（5分钟）"],
        "transport_note": "JR全线/地铁换乘枢纽，去富良野/函馆出发点",
        "area_type": "city_center",
        "budget_tier": "mid",
    },
    {
        "area_name": "薄野・中岛公园",
        "city_code": "sapporo",
        "description_zh": (
            "薄野是北海道最大的夜生活区，居酒屋/炭烧/成吉思汗集中在此。"
            "中岛公园側酒店环境更安静，步行15分钟即到薄野热闹区。"
            "不介意深夜偶尔有声音的旅客，在这里吃饭宵夜最方便，不需要考虑交通。"
        ),
        "typical_price_range": "¥7000-18000/晚",
        "recommended_for": ["爱夜生活/居酒屋的旅客", "想吃成吉思汗/炭烧的"],
        "walking_highlights": ["薄野美食街（步行即达）", "中岛公园（5分钟）"],
        "transport_note": "地铁薄野站/中島公園站，去大通10分钟",
        "area_type": "entertainment_district",
        "budget_tier": "mid",
    },
    {
        "area_name": "円山・西区",
        "city_code": "sapporo",
        "description_zh": (
            "札幌最有品质感的住宅区，远离市中心喧闹，"
            "円山公园+北海道神宫就在旁边，附近有独立咖啡馆和小型食堂。"
            "适合想慢节奏感受「真实札幌生活」而非商业旅游面孔的旅客。"
        ),
        "typical_price_range": "¥10000-22000/晚（主要为精品酒店/民宿）",
        "recommended_for": ["慢旅行者", "喜欢咖啡馆文化", "想避开市中心喧嚣"],
        "walking_highlights": ["円山公园（5分钟）", "北海道神宫（15分钟）"],
        "transport_note": "地铁东西线円山公園站，去札幌站15分钟",
        "area_type": "residential_quality",
        "budget_tier": "mid",
    },
    # ── 函馆 ──────────────────────────────────────────────────────────────────
    {
        "area_name": "湯の川温泉",
        "city_code": "hakodate",
        "description_zh": (
            "函馆最集中的温泉旅馆区，约30家温泉旅馆聚集，可泡温泉可看津轻海峡海景。"
            "距函馆市中心市电约20分钟，距函馆山单程约30分钟。"
            "「朝市+夜景+温泉」三件套的最优解住宿地，推荐住至少1晚温泉旅馆。"
        ),
        "typical_price_range": "¥12000-35000/晚（含两食）",
        "recommended_for": ["想泡温泉", "函馆完整体验（朝市+夜景+温泉）", "情侣/夫妻"],
        "walking_highlights": ["湯の川温泉街（步行即达）", "函馆市电站（5分钟）"],
        "transport_note": "市电「湯の川」终点站，打车去函馆山约¥2500",
        "area_type": "onsen_ryokan",
        "budget_tier": "premium",
    },
    {
        "area_name": "函馆站周边",
        "city_code": "hakodate",
        "description_zh": (
            "函馆车站前聚集了主要商务酒店，步行至朝市3分钟，交通换乘方便。"
            "元町/函馆山方向打车¥1500内可到，适合行程紧凑、不打算泡温泉的旅客。"
            "价格比湯の川低，但无温泉服务。"
        ),
        "typical_price_range": "¥8000-18000/晚",
        "recommended_for": ["行程紧凑的旅客", "不需要温泉的旅客"],
        "walking_highlights": ["函馆朝市（3分钟）", "函馆駅（步行即达）"],
        "transport_note": "JR函馆駅前，去五棱郭市电10分钟",
        "area_type": "city_center",
        "budget_tier": "mid",
    },
    # ── 富良野 ────────────────────────────────────────────────────────────────
    {
        "area_name": "富良野市区（中富良野周边）",
        "city_code": "furano",
        "description_zh": (
            "夏季薰衣草旺季的住宿中心，步行或骑车可到Farm Tomita。"
            "选择从经济民宿到中档酒店均有，但数量有限，旺季（7-8月）需提前3个月以上预订。"
            "周边农场民宿（農家民宿）提供最接地气的北海道农家体验。"
        ),
        "typical_price_range": "¥6000-18000/晚（民宿¥3500起）",
        "recommended_for": ["薰衣草旺季（7月）专程来的旅客", "想深度体验北海道农场生活"],
        "walking_highlights": ["Farm Tomita（骑车15分钟）", "富良野チーズ工房"],
        "transport_note": "JR富良野線各站，旺季有ラベンダー号观光列车",
        "area_type": "countryside",
        "budget_tier": "budget",
    },
    # ── 知床 ──────────────────────────────────────────────────────────────────
    {
        "area_name": "ウトロ温泉（知床）",
        "city_code": "abashiri",
        "description_zh": (
            "知床半岛西侧唯一的住宿集中地，约15家温泉旅馆/酒店，面向鄂霍次克海。"
            "知床五湖/知床峠/知床自然中心步行或打车均可达。"
            "夏季（6-10月）必须提前2-4周预订；春秋季相对宽松但也建议提早。"
        ),
        "typical_price_range": "¥15000-40000/晚（多含两食）",
        "recommended_for": ["世界遗产深度游", "看熊/鹿/鲑鱼洄游（秋季）", "日出观看"],
        "walking_highlights": ["知床自然中心（步行即达）", "オロンコ岩（5分钟）"],
        "transport_note": "网走→ウトロ约1.5小时（巴士/自驾），无JR直达",
        "area_type": "nature_resort",
        "budget_tier": "premium",
    },
    # ── 洞爷湖 ────────────────────────────────────────────────────────────────
    {
        "area_name": "洞爷湖温泉",
        "city_code": "sapporo",
        "description_zh": (
            "洞爷湖畔的温泉旅馆区，湖景+温泉+有珠山活火山三者合一。"
            "距札幌约2小时车程，常作为「往返札幌途中一晚中转」使用。"
            "夏季湖面夜间有烟火大会（4月下旬-10月下旬每晚），从旅馆阳台即可观看。"
        ),
        "typical_price_range": "¥15000-45000/晚（多含两食）",
        "recommended_for": ["温泉休闲", "拍活火山+湖景", "情侣浪漫夜"],
        "walking_highlights": ["洞爷湖畔散步道（步行即达）", "西山火口散策路（步行30分钟）"],
        "transport_note": "JR洞爺駅→巴士20分钟到湖畔，或租车自驾",
        "area_type": "onsen_resort",
        "budget_tier": "premium",
    },
]


# ─────────────────────────────────────────────────────────────────────────────
# Seed 执行逻辑（与 kansai_entities_seed.py 保持同样结构）
# ─────────────────────────────────────────────────────────────────────────────

async def seed():
    """将北海道实体数据 upsert 到数据库。"""
    try:
        from app.db.session import AsyncSessionLocal
        from app.db.seed.kansai_entities_seed import upsert_entities
    except ImportError:
        logger.error(
            "无法导入数据库模块，请在项目根目录运行: python scripts/seed_hokkaido_entities.py"
        )
        return

    async with AsyncSessionLocal() as session:
        poi_count = await upsert_entities(session, HOKKAIDO_POIS, "poi", "hokkaido")
        rest_count = await upsert_entities(session, HOKKAIDO_RESTAURANTS, "restaurant", "hokkaido")
        area_count = await upsert_entities(session, HOKKAIDO_HOTEL_AREAS, "hotel_area", "hokkaido")
        await session.commit()

    print(f"✅ 北海道 seed 完成：{poi_count} 景点 / {rest_count} 餐厅 / {area_count} 住宿区域")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(seed())
